### ISSUE TITLE
Ivony.Data.SqlClient.SqlDbExecutor 中的 Execute、ExecuteAsync 等方法有 Object reference not set to an instance of an object. 异常

### ISSUE THREAD

**Issue by jtying** [Ivony/DataPithy#1]
if (Configuration.QueryExecutingTimeout.HasValue)
   command.CommandTimeout = (int)Configuration.QueryExecutingTimeout.Value.TotalSeconds;

会引起 System.NullReferenceException:“Object reference not set to an instance of an object.”
Ivony.Data.SqlClient.SqlDbExecutor.Configuration.get 返回 null。

**Comment by hulukaihuaba** [comment]
你好我也碰到了这个问题，请问你后面有解决吗？刚开始学c#不太了解，感觉是初始化的时候iserviceprovider没有设置为空引起的，但是我不知道要怎么设置

**Comment by jtying** [comment]
一开始我是到源码里，把出错的地方屏蔽掉了，然后重新生成dll。

后来就换了Dapper，FreeSQL 这些比较流行的ORM库。Dapper 的用法和这个差不多，看下几个示例就会了。

hulukaihuaba ***@***.***>于2022年2月23日 周三10:28写道：

**Comment by hulukaihuaba** [comment]
谢谢回答，我也是把为空的那个对象的使用方法注释掉了，我去学习下你说的这两个库

**Comment by Ivony** [comment]
fixed in commit d7f467c6ecfe8e11ded449b756d7d796777c9710
